<?php

namespace AppBundle\Repository;

/**
 * Graf
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Graf extends \Doctrine\ORM\EntityRepository
{
}
